version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./gradlew build
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./gradlew test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
